# Generated by Django 4.1.2 on 2023-05-28 07:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_match_id_alter_profile_id_alter_profile_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cb1e3262-4a36-4247-a264-3e0e1866e4da'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7c6db033-f85b-4b64-a912-046e5d70eb56'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tags',
        ),
        migrations.AddField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(to='core.tag'),
        ),
    ]
